routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
}); */

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('pages', 'PagesController');
Route::get('/snippets/snippet', 'PagesController@snippets')->name('pages.snippets');
Route::resource('themes', 'ThemesController');

Route::post('pages/savehtml', 'PagesController@savehtml')->name('pages.savehtml');
Route::post('pages/saveimage', 'PagesController@saveimage')->name('pages.saveimage');
Route::post('pages/savecover', 'PagesController@savecover')->name('pages.savecover');

Route::get('settings/header', 'SettingsController@header')->name('settings.header');
Route::get('settings/menu', 'SettingsController@menu')->name('settings.menu');
Route::get('settings/footer', 'SettingsController@footer')->name('settings.footer');
Route::get('settings/fonts', 'SettingsController@fonts')->name('settings.fonts');
Route::get('settings/colors', 'SettingsController@colors')->name('settings.colors');
Route::get('/seeder', 'CreateSeeder@index');

resources/views/admin/colors.blade.php
@extends('layouts.app')

@section('extra')


<style>

</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<h4 class="page-title">Header Settings</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				<div class="card-box">
					
				</div>
			</div>
    </div>
</div>

@endsection

resources/views/admin/fonts.blade.php
@extends('layouts.app')

@section('extra')


<style>

</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<h4 class="page-title">Fonts Settings</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				<div class="card-box">
					
				</div>
			</div>
    </div>
</div>

@endsection

resources/views/admin/footer.blade.php
@extends('layouts.app')

@section('extra')


<style>

</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<h4 class="page-title">Footer Settings</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				<div class="card-box">
					
				</div>
			</div>
    </div>
</div>

@endsection

resources/views/admin/header.blade.php
@extends('layouts.app')

@section('extra')


<style>

</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<h4 class="page-title">Header Settings</h4>
			</div>
    </div>
	<div class="row">
		<div class="col-sm-6 m-t-15">	
			<div class="card-box">
				
			</div>
		</div>
		<div class="col-sm-6 m-t-15">	
			<div class="card-box">
				
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/menu.blade.php
@extends('layouts.app')

@section('extra')


<style>

</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<h4 class="page-title">Menu Settings</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				<div class="card-box">
					
				</div>
			</div>
    </div>
</div>

@endsection

resources/views/admin/pages.blade.php
@extends('layouts.app')

@section('extra')

<link href="{{ asset('assets/plugins/datatables/dataTables.colVis.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/plugins/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/plugins/datatables/fixedColumns.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
<style>
.buttons{
	display: none;
    padding: 0;
    margin: 0;
}
.buttons li{
	display: inline-block;
    margin-right: 10px;
    font-size: 13px;
    padding-left: 10px;
    border-left: 1px solid #cccccc;
    line-height: 1;
}
.buttons li:first-child{
	border:0;
	padding:0;
}
.table tr:hover .buttons{
	display:block;
}
</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<div class="btn-group pull-right">
					<button class="btn btn-default waves-effect waves-light btn-sm pull-right" data-toggle="modal" data-target="#con-close-modal">Add New Page</button>
				</div>
				<h4 class="page-title">All Pages</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				<div class="card-box">
					<table id="datatable-buttons" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Name</th>
								<th>Slug</th>
								<th>Created on</th>
							</tr>
						</thead>
						<tbody>
							@foreach (json_decode($pages) as $page)
							<tr>
								<td>
								{{ $page->title }}
								<ul class="buttons">
									<li><a href="">View</a></li>
									<li><a href="{{URL::route('pages.edit', $page->id)}}">Edit</a></li>
									<li><a href="">Trash</a></li>
								</ul>
								</td>
								<td>{{ $page->slug }}</td>
								<td>Published<br />{{ $page->created_at }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
    </div>
</div>

<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog"> 
		<div class="modal-content"> 
			<div class="modal-header"> 
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> 
				<h4 class="modal-title">Create New Page</h4> 
			</div> 
			<div class="modal-body"> 
				<div class="row"> 
					<form method="POST" id="createpageform" action="">
					{{ csrf_field() }}
					<div class="col-md-12"> 
						<div class="form-group"> 
							<label for="field-1" class="control-label">Title</label> 
							<input type="text" name="title" class="form-control" id="field-1" placeholder="" required> 
						</div> 
					</div> 
					<div class="col-md-12"> 
						<div class="form-group"> 
							<label for="field-2" class="control-label">Slug</label> 
							<input type="text" name="slug" class="form-control" id="field-2" placeholder="" > 
						</div> 
					</div> 
					</form>
				</div> 
			</div> 
			<div class="modal-footer"> 
				<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button> 
				<button type="button" id="save" class="btn btn-info waves-effect waves-light">Add Page</button> 
			</div> 
		</div> 
	</div>
</div><!-- /.modal -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.fixedHeader.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/responsive.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.colVis.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.fixedColumns.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
<script>
$(document).ready(function(){
	$('#save').on('click', function(){
		$('#createpageform input[type="text"]').removeClass('parsley-error');
		$.ajax({
            type: "POST",
            url: '{{URL::route('pages.store')}}',
            data: $("#createpageform").serialize(),
            success: function( msg ) {
                if(msg == 'success'){
					window.location.href = "{{URL::route('pages.index')}}";
				}else{
					var obj = jQuery.parseJSON(msg);
					if(obj.error.length>0){
						for(var i = 0; i<obj.error.length; i++){
							$('input[name="'+obj.error[i].field+'"]').addClass('parsley-error');
						}
					}
				}
            }
        });
	})
	TableManageButtons.init();
})
</script>

@endsection

resources/views/admin/themes.blade.php
@extends('layouts.app')

@section('extra')


@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<div class="btn-group pull-right">
					<button class="btn btn-default waves-effect waves-light btn-sm pull-right" data-toggle="modal" data-target="#con-close-modal">Add New Theme</button>
				</div>
				<h4 class="page-title">All Themes</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				
				<div class="row port">
					<div class="portfolioContainer">
						@foreach($themes as $theme)
						<div class="col-sm-6 col-lg-4 col-md-4 webdesign illustrator">
							<div class="gal-detail thumb">
								<img src="{{ asset('/templates/'.$theme['name'].'/screenshot.png') }}" class="thumb-img" alt="work-thumbnail">
								<div class="row">
									<div class="col-xs-4  m-t-15">
									<h5>{{ $theme['name'] }}</h5>
									</div>
									<div class="col-xs-8 m-t-15 text-right">
									@if($theme['active'])
									<button type="button" class="btn btn-info btn-rounded waves-effect waves-light" disabled><span class="btn-label"><i class="fa fa-check"></i></span>Activated</button>
									@else
									<button type="button" class="btn btn-info btn-rounded waves-effect waves-light">Active</button>
									@endif
									<button style="margin-left:10px;" type="button" class="btn btn-danger btn-rounded waves-effect waves-light">Remove</button>
									</div>
								</div>
							</div>
						</div>
						@endforeach
					</div>
				</div> <!-- End row -->
				
			</div>
    </div>
</div>

<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog"> 
		<div class="modal-content"> 
			<div class="modal-header"> 
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> 
				<h4 class="modal-title">Create New Page</h4> 
			</div> 
			<div class="modal-body"> 
				<div class="row"> 
					<form method="POST" id="createpageform" action="">
					{{ csrf_field() }}
					<div class="col-md-12"> 
						<div class="form-group"> 
							<label for="field-1" class="control-label">Title</label> 
							<input type="text" name="title" class="form-control" id="field-1" placeholder="" required> 
						</div> 
					</div> 
					<div class="col-md-12"> 
						<div class="form-group"> 
							<label for="field-2" class="control-label">Slug</label> 
							<input type="text" name="slug" class="form-control" id="field-2" placeholder="" > 
						</div> 
					</div> 
					</form>
				</div> 
			</div> 
			<div class="modal-footer"> 
				<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button> 
				<button type="button" id="save" class="btn btn-info waves-effect waves-light">Add Page</button> 
			</div> 
		</div> 
	</div>
</div><!-- /.modal -->
<script type="text/javascript" src="{{ asset('assets/plugins/isotope/js/isotope.pkgd.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/magnific-popup/js/jquery.magnific-popup.min.js') }}"></script>
<script type="text/javascript">
	$(window).load(function(){
		var $container = $('.portfolioContainer');
		$container.isotope({
			filter: '*',
			animationOptions: {
				duration: 750,
				easing: 'linear',
				queue: false
			}
		});

		$('.portfolioFilter a').click(function(){
			$('.portfolioFilter .current').removeClass('current');
			$(this).addClass('current');

			var selector = $(this).attr('data-filter');
			$container.isotope({
				filter: selector,
				animationOptions: {
					duration: 750,
					easing: 'linear',
					queue: false
				}
			});
			return false;
		}); 
	});
	$(document).ready(function() {
		$('.image-popup').magnificPopup({
			type: 'image',
			closeOnContentClick: true,
			mainClass: 'mfp-fade',
			gallery: {
				enabled: true,
				navigateByImgClick: true,
				preload: [0,1] // Will preload 0 - before current, and 1 after the current image
			}
		});
	});
</script>

@endsection